### PR TITLE
Cleanup some Wrangler code

### PR DESCRIPTION
**Pull request by Denton-L**
Just some minor code cleanup while looking around the codebase and getting a feel for it.

### CODE REVIEW

**Comment by nitinmotgi** [comment]
@Denton-L Checks are failing ... can you please make sure tests pass.

**Comment by Denton-L** [comment]
@nitinmotgi seems like Travis is borked because of S3. I'll rerun the build whenever that gets fixed.

**Comment by nitinmotgi** [comment]
Will review it when the builds are successful. Both builds

**Comment by Denton-L** [comment]
@nitinmotgi, builds have finally passed!

**Pull request merged**
