### PR TITLE
Handle oracle's ROWID datatype

### PR DESCRIPTION
**Pull request by CuriousVini**
Issue: https://issues.cask.co/browse/CDAP-12639

image

Tested the fix. Here RID is a `RowId` type.

### CODE REVIEW

**Comment by bdmogal** [comment]
@CuriousVini does this work when you create a pipeline/ingest data?

**Comment by CuriousVini** [comment]
@bdmogal Does it throw same exception when used in pipeline as well?

**Comment by bdmogal** [comment]
@CuriousVini I am not sure, but we should test the end-to-end flow, since we've discovered this issue in Data Prep.

**Comment by CuriousVini** [comment]
Agreed. I will test that. But I think the fix will go in Database source/hydrator.

**Comment by bdmogal** [comment]
lgtm, presuming further testing of database source done separately.

**Pull request merged**
