### PR TITLE
Feature/merge rel32 to dev

### PR DESCRIPTION
**Pull request by rohitsinha54**

### CODE REVIEW

**Comment by albertshau** [comment]
There are no differences, does this need to be done?

**Comment by rohitsinha54** [comment]
It is nice to have. Since it will create the commit history for the release version on develop. So later if we merge something on release or bump to snapshot on release again we will not have conflict due to this commit.

**Comment by rohitsinha54** [comment]
Also it keeps the release and develop commits history tree in sync which I think we should have.

**Comment by albertshau** [comment]
As we discussed in person, please open another PR to bump the version on release after this is merged.

**Review by albertshau — APPROVED** [review]

**Review by albertshau — APPROVED** [review]

**Pull request merged**
