### PR TITLE
[CDAP-15220] Allow discovery of wrangler service running in system namespace

### PR DESCRIPTION
**Pull request by miguelvelezmj25**
JIRA: https://issues.cask.co/browse/CDAP-15220

### CODE REVIEW

**Comment by miguelvelezmj25** [comment]
https://builds.cask.co/browse/HYP-WT315/

**Comment by miguelvelezmj25** [comment]
Currently, the build is not passing since the fix in cdap (https://github.com/cdapio/cdap/pull/11369) has not been merged yet.

**Review by albertshau — APPROVED** [review]
lgtm, but please wait for your change in CDAP to merge and for a snapshot version with the change to make it to maven (this should happen after a successful run of https://builds.cask.co/browse/CDAP-BUT).

**Comment by miguelvelezmj25** [comment]
The wrangler build passed, but I will not merge this change until the cdap build also passes.

**Pull request merged**
